#!/bin/bash

TEMPDIR=`mktemp -d`
BABEL=node_modules/.bin/babel
BROWSERIFY=node_modules/.bin/browserify
OUT_FILE=kanjiapi-wrapper.min.js

rm $OUT_FILE
$BABEL *[^test].js --preset=@babel/env --presets minify --out-dir $TEMPDIR
$BROWSERIFY -o $OUT_FILE

rm -rf $TEMPDIR
