#!/bin/bash

TEMPDIR=`mktemp -d`
BABEL=node_modules/.bin/babel
BROWSERIFY=node_modules/.bin/browserify
OUT_FILE=kanjiapi-wrapper.min.js

rm $OUT_FILE

$BROWSERIFY --entry browser.js --outfile $OUT_FILE
$BABEL $OUT_FILE --preset=@babel/env --presets minify --out-file $OUT_FILE

rm -rf $TEMPDIR
